import { defineAiSdr, defaultOrchidModules, providersFromModules } from "@ai-sdr/framework";

const modules = defaultOrchidModules().filter((module) => module.id !== "neon");

export default defineAiSdr({
  name: "orchid-sdr",
  description: "Reference implementation for a self-hostable, composable AI SDR control plane.",
  compositionTargets: ["minimum", "productionParity"],
  modelRouting: {
    defaultModel: "moonshotai/kimi-k2.6",
    sandbox: {
      defaultModel: "moonshotai/kimi-k2.6",
      stages: {
        discovery: "moonshotai/kimi-k2.6",
        qualify: "moonshotai/kimi-k2.6",
        build_research_brief: "moonshotai/kimi-k2.6",
        first_outbound: "moonshotai/kimi-k2.6",
        await_reply: "moonshotai/kimi-k2.6",
        classify_reply: "moonshotai/kimi-k2.6",
        respond_or_handoff: "moonshotai/kimi-k2.6",
      },
    },
    structured: {
      classifyReply: "moonshotai/kimi-k2.6",
      policyCheck: "moonshotai/kimi-k2.6",
      qualifyProspect: "moonshotai/kimi-k2.6",
    },
  },
  knowledge: {
    product: "knowledge/product.md",
    icp: "knowledge/icp.md",
    usp: "knowledge/usp.md",
    compliance: "knowledge/compliance.md",
    negativeSignals: "knowledge/negative-signals.md",
    handoff: "knowledge/handoff.md",
  },
  skills: [
    {
      id: "icp-qualification",
      path: "skills/icp-qualification",
      description: "Qualify prospects against the repo-managed ICP.",
    },
    {
      id: "research-brief",
      path: "skills/research-brief",
      description: "Turn source evidence into a concise research brief.",
    },
    {
      id: "research-checks",
      path: "skills/research-checks",
      description: "Validate source quality and research sufficiency.",
    },
    {
      id: "sdr-copy",
      path: "skills/sdr-copy",
      description: "Draft outbound copy from approved evidence.",
    },
    {
      id: "reply-policy",
      path: "skills/reply-policy",
      description: "Classify replies and choose next steps.",
    },
    {
      id: "handoff-policy",
      path: "skills/handoff-policy",
      description: "Decide when to route a lead to a human.",
    },
  ],
  modules,
  providers: providersFromModules(modules),
  capabilityBindings: [
    {
      capabilityId: "state",
      providerId: "convex",
      contractId: "state.reactive.v1",
      default: true,
    },
    {
      capabilityId: "source",
      providerId: "normalized-webhook",
      contractId: "signal.webhook.v1",
      purpose: "warm_inbound",
      default: true,
    },
    {
      capabilityId: "source",
      providerId: "apify-linkedin",
      contractId: "signal.discovery.v1",
      purpose: "discovery",
      default: true,
    },
    {
      capabilityId: "search",
      providerId: "firecrawl",
      contractId: "research.search.v1",
      default: true,
    },
    {
      capabilityId: "extract",
      providerId: "firecrawl",
      contractId: "research.extract.v1",
      default: true,
    },
    {
      capabilityId: "search",
      providerId: "parallel",
      contractId: "research.deepResearch.v1",
      purpose: "deep_research",
    },
    {
      capabilityId: "observability",
      providerId: "parallel",
      contractId: "research.monitor.v1",
      purpose: "monitor",
    },
    {
      capabilityId: "enrichment",
      providerId: "prospeo",
      contractId: "research.enrich.v1",
      purpose: "contact_email",
      default: true,
    },
    {
      capabilityId: "model",
      providerId: "vercel-ai-gateway",
      contractId: "model.gateway.v1",
      default: true,
    },
    {
      capabilityId: "runtime",
      providerId: "rivet",
      contractId: "runtime.actor.v1",
      default: true,
    },
    {
      capabilityId: "runtime",
      providerId: "vercel-sandbox",
      contractId: "runtime.sandbox.v1",
      default: true,
    },
    {
      capabilityId: "email",
      providerId: "agentmail",
      contractId: "email.outbound.v1",
      default: true,
    },
    {
      capabilityId: "email",
      providerId: "agentmail",
      contractId: "email.inbound.v1",
      default: true,
    },
    {
      capabilityId: "crm",
      providerId: "attio",
      contractId: "crm.prospectSync.v1",
      default: true,
    },
    {
      capabilityId: "crm",
      providerId: "attio",
      contractId: "crm.stageUpdate.v1",
      default: true,
    },
    {
      capabilityId: "handoff",
      providerId: "slack-handoff",
      contractId: "handoff.notify.v1",
      default: true,
    },
    {
      capabilityId: "mcp",
      providerId: "orchid-mcp",
      contractId: "mcp.tools.v1",
      default: true,
    },
  ],
  packageBoundaries: [
    {
      id: "framework-core",
      packageName: "@ai-sdr/framework",
      visibility: "public",
      description: "Capability schema, contracts, config validation, composition logic, and installation planning.",
      capabilityIds: ["source", "search", "extract", "enrichment", "runtime", "model", "crm", "email", "handoff", "state", "mcp"],
    },
    {
      id: "ai-sdr-source-webhooks",
      packageName: "@ai-sdr/webhooks",
      visibility: "public",
      moduleIds: ["normalized-webhook"],
      providerIds: ["normalized-webhook"],
      capabilityIds: ["source"],
      contractIds: ["signal.webhook.v1", "signal.normalized.v1"],
    },
    {
      id: "ai-sdr-source-apify-linkedin",
      packageName: "@ai-sdr/apify-linkedin",
      visibility: "public",
      moduleIds: ["apify-linkedin"],
      providerIds: ["apify-linkedin"],
      capabilityIds: ["source"],
      contractIds: ["signal.discovery.v1", "signal.normalized.v1"],
    },
    {
      id: "ai-sdr-search-parallel",
      packageName: "@ai-sdr/parallel",
      visibility: "public",
      description: "Deep research, monitoring, and async web-task orchestration.",
      moduleIds: ["parallel"],
      providerIds: ["parallel"],
      capabilityIds: ["search", "extract", "enrichment", "source", "observability"],
      contractIds: ["research.search.v1", "research.extract.v1", "research.deepResearch.v1", "research.enrich.v1", "research.monitor.v1", "signal.discovery.v1"],
    },
    {
      id: "ai-sdr-extract-firecrawl",
      packageName: "@ai-sdr/firecrawl",
      visibility: "public",
      description: "Primary web search and extraction surface for the reference AI SDR stack.",
      moduleIds: ["firecrawl"],
      providerIds: ["firecrawl"],
      capabilityIds: ["search", "extract", "enrichment", "source", "runtime", "observability"],
      contractIds: ["research.search.v1", "research.extract.v1"],
    },
    {
      id: "ai-sdr-enrichment-prospeo",
      packageName: "@ai-sdr/prospeo",
      visibility: "public",
      moduleIds: ["prospeo"],
      providerIds: ["prospeo"],
      capabilityIds: ["enrichment"],
      contractIds: ["research.enrich.v1"],
    },
    {
      id: "ai-sdr-crm-attio",
      packageName: "@ai-sdr/attio",
      visibility: "public",
      moduleIds: ["attio"],
      providerIds: ["attio"],
      capabilityIds: ["crm"],
      contractIds: ["crm.prospectSync.v1", "crm.stageUpdate.v1"],
    },
    {
      id: "ai-sdr-email-agentmail",
      packageName: "@ai-sdr/agentmail",
      visibility: "public",
      moduleIds: ["agentmail"],
      providerIds: ["agentmail"],
      capabilityIds: ["email"],
      contractIds: ["email.outbound.v1", "email.inbound.v1"],
    },
    {
      id: "ai-sdr-state-convex",
      packageName: "@ai-sdr/convex",
      visibility: "public",
      moduleIds: ["convex"],
      providerIds: ["convex"],
      capabilityIds: ["state"],
      contractIds: ["state.reactive.v1", "state.workflow.v1", "state.agentThreads.v1", "state.auditLog.v1"],
    },
    {
      id: "ai-sdr-runtime-rivet",
      packageName: "@ai-sdr/rivet",
      visibility: "public",
      moduleIds: ["rivet"],
      providerIds: ["rivet"],
      capabilityIds: ["runtime"],
      contractIds: ["runtime.actor.v1"],
    },
    {
      id: "ai-sdr-runtime-vercel-sandbox",
      packageName: "@ai-sdr/vercel-sandbox",
      visibility: "public",
      moduleIds: ["vercel-sandbox"],
      providerIds: ["vercel-sandbox"],
      capabilityIds: ["runtime"],
      contractIds: ["runtime.sandbox.v1"],
    },
    {
      id: "ai-sdr-model-vercel-ai-gateway",
      packageName: "@ai-sdr/vercel-ai-gateway",
      visibility: "public",
      moduleIds: ["vercel-ai-gateway"],
      providerIds: ["vercel-ai-gateway"],
      capabilityIds: ["model"],
      contractIds: ["model.gateway.v1"],
    },
    {
      id: "ai-sdr-handoff-slack",
      packageName: "@ai-sdr/slack",
      visibility: "public",
      moduleIds: ["slack-handoff"],
      providerIds: ["slack-handoff"],
      capabilityIds: ["handoff"],
      contractIds: ["handoff.notify.v1"],
    },
    {
      id: "ai-sdr-mcp",
      packageName: "@ai-sdr/mcp",
      visibility: "public",
      moduleIds: ["orchid-mcp"],
      providerIds: ["orchid-mcp"],
      capabilityIds: ["mcp"],
      contractIds: ["mcp.tools.v1"],
    },
  ],
  campaigns: [
    {
      id: "cmp_default",
      timezone: "America/New_York",
      noSendsMode: true,
      sources: ["normalized-webhook", "apify-linkedin"],
    },
  ],
  webhooks: [
    {
      id: "signals",
      displayName: "Normalized signals ingest",
      description: "Warm leads and custom upstream sources post normalized signal payloads here.",
      method: "POST",
      path: "/webhooks/signals",
      providerId: "normalized-webhook",
      secretEnv: "SIGNAL_WEBHOOK_SECRET",
      fallbackSecretEnv: "APIFY_WEBHOOK_SECRET",
      auth: "shared-secret-query-or-header",
      authKey: "secret",
    },
    {
      id: "apify",
      displayName: "Apify discovery webhook",
      description: "Apify run-completion callbacks land here for discovery ingestion.",
      method: "POST",
      path: "/webhooks/apify",
      providerId: "apify-linkedin",
      secretEnv: "APIFY_WEBHOOK_SECRET",
      auth: "shared-secret-query-or-header",
      authKey: "secret",
      eventTypes: ["ACTOR.RUN.SUCCEEDED", "TASK.RUN.SUCCEEDED"],
    },
    {
      id: "agentmail",
      displayName: "AgentMail inbound reply webhook",
      description: "AgentMail posts signed inbound message events here.",
      method: "POST",
      path: "/webhooks/agentmail",
      providerId: "agentmail",
      secretEnv: "AGENTMAIL_WEBHOOK_SECRET",
      auth: "svix-signature",
      eventTypes: ["message.received"],
    },
    {
      id: "handoff",
      displayName: "Signed handoff callback",
      description: "Internal or external handoff systems can record thread disposition here.",
      method: "POST",
      path: "/webhooks/handoff",
      secretEnv: "HANDOFF_WEBHOOK_SECRET",
      auth: "hmac-header",
      authKey: "x-orchid-signature",
    },
  ],
  requiredEnv: [
    { name: "APP_URL", required: true, description: "Public app URL used by sandboxes and webhooks." },
    { name: "CONVEX_URL", required: true, description: "Convex deployment URL used by the runtime repository and state plane." },
    { name: "HANDOFF_WEBHOOK_SECRET", required: true, description: "Shared secret for handoff webhooks." },
  ],
});
