import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  workspaces: defineTable({
    key: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
  meetings: defineTable({
    id: v.string(),
    source: v.string(),
    externalId: v.optional(v.string()),
    title: v.string(),
    startsAt: v.string(),
    endsAt: v.optional(v.string()),
    organizerEmail: v.optional(v.string()),
    accountName: v.optional(v.string()),
    notes: v.optional(v.string()),
    attioRecordId: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_meeting_key", ["id"]).index("by_external", ["source", "externalId"]).index("by_updated", ["updatedAt"]),
  attendees: defineTable({
    id: v.string(),
    meetingId: v.string(),
    fullName: v.string(),
    email: v.optional(v.string()),
    company: v.optional(v.string()),
    role: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_attendee_key", ["id"]).index("by_meeting", ["meetingId"]),
  prepRuns: defineTable({
    id: v.string(),
    meetingId: v.string(),
    status: v.string(),
    stage: v.string(),
    summary: v.optional(v.string()),
    error: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_prep_run_key", ["id"]).index("by_meeting", ["meetingId"]).index("by_updated", ["updatedAt"]),
  prepBriefs: defineTable({
    meetingId: v.string(),
    kind: v.string(),
    title: v.string(),
    content: v.string(),
    structured: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_meeting", ["meetingId"]).index("by_updated", ["updatedAt"]),
  auditEvents: defineTable({
    entityType: v.string(),
    entityId: v.string(),
    eventName: v.string(),
    payload: v.optional(v.any()),
    createdAt: v.number(),
  }).index("by_entity", ["entityType", "entityId"]).index("by_created", ["createdAt"]),
});
